[package]
name = "oxabl"
version = "0.1.0"
edition = "2024"

[dependencies]
oxabl_parser = { path = "../oxabl_parser" }
oxabl_lexer = { path = "../oxabl_lexer" }
oxabl_common = { path = "../oxabl_common" }
oxabl_ast = { path = "../oxabl_ast" }
